"""Natural Earth public-domain 1:50m outline. Albers 50/70N, centered 100E.
Inputs cached in artifacts/stage-2; URLs and provenance in ASSETS.md.
"""
import json
from pathlib import Path
from pyproj import Transformer
from shapely.geometry import shape
from shapely.ops import transform
root=Path(__file__).resolve().parents[2]
features=json.loads((root/'artifacts/stage-2/countries-50m.geojson').read_text())['features']
geo=next(f for f in features if f['properties']['ADMIN']=='Russia')
project=Transformer.from_crs('EPSG:4326','+proj=aea +lat_1=50 +lat_2=70 +lat_0=60 +lon_0=100 +datum=WGS84',always_xy=True)
g=transform(project.transform,shape(geo['geometry'])).simplify(4200,preserve_topology=True)
x0,y0,x1,y1=g.bounds;scale=min(1120/(x1-x0),590/(y1-y0))
def point(x,y):return [round(40+(x-x0)*scale,1),round(30+(y1-y)*scale,1)]
paths=[]
for poly in g.geoms:
 for ring in [poly.exterior,*poly.interiors]:
  pts=[point(x,y) for x,y in ring.coords];paths.append('M'+'L'.join(f'{x},{y}' for x,y in pts)+'Z')
path=''.join(paths)
(root/'src/content/russia-outline.ts').write_text('// Generated by scripts/geo/build-map.py from Natural Earth 1:50m. Public domain.\nexport const russiaOutline = '+json.dumps(path)+';\n')
names=[('Moscow','Москва','moscow',True,'В пределах города'),('St.  Petersburg','Санкт-Петербург','saint-petersburg',True,'1–2 дня'),('Nizhny Novgorod','Нижний Новгород','nizhny-novgorod',False,'1–2 дня'),('Kazan','Казань','kazan',True,'2–3 дня'),('Samara','Самара','samara',False,'2–3 дня'),('Voronezh','Воронеж','voronezh',False,'1–2 дня'),('Rostov','Ростов-на-Дону','rostov',False,'2–3 дня'),('Krasnodar','Краснодар','krasnodar',True,'2–3 дня'),('Yekaterinburg','Екатеринбург','ekaterinburg',True,'3–4 дня'),('Chelyabinsk','Челябинск','chelyabinsk',False,'3–4 дня'),('Perm','Пермь','perm',False,'3–4 дня'),('Ufa','Уфа','ufa',False,'3–4 дня'),('Tyumen','Тюмень','tyumen',False,'4–5 дней'),('Omsk','Омск','omsk',False,'5–6 дней'),('Novosibirsk','Новосибирск','novosibirsk',True,'5–6 дней'),('Krasnoyarsk','Красноярск','krasnoyarsk',False,'7–8 дней'),('Irkutsk','Иркутск','irkutsk',False,'8–9 дней'),('Vladivostok','Владивосток','vladivostok',False,'13–14 дней')]
places=json.loads((root/'artifacts/stage-2/cities-natural-earth.geojson').read_text())['features'];cities=[]
for en,ru,id,warehouse,days in names:
 candidates=[f['properties'] for f in places if f['properties']['name']==en and f['properties'].get('adm0name')=='Russia']
 p=min(candidates,key=lambda p:p['latitude']) # Rostov-on-Don rather than Rostov Veliky.
 lon,lat=p['longitude'],p['latitude'];x,y=point(*project.transform(lon,lat));cities.append(dict(id=id,name=ru,latitude=lat,longitude=lon,x=x,y=y,warehouse=warehouse,days=days))
(root/'src/content/cities.ts').write_text('// Coordinates: Natural Earth populated places 1:10m. Delivery times are fictional demo data.\nexport const cities = '+json.dumps(cities,ensure_ascii=False,indent=2)+' as const;\nexport type City = (typeof cities)[number];\n')
svg=f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 650"><path fill="#F2F4F7" stroke="#D0D5DD" stroke-width="1" d="{path}"/>'
m=cities[0]
for c in cities:
 if c['warehouse'] and c!=m:svg+=f'<path d="M{m["x"]},{m["y"]} Q{(m["x"]+c["x"])/2},{min(m["y"],c["y"])-60} {c["x"]},{c["y"]}" fill="none" stroke="#0B2A4A" stroke-width="1.5"/>'
for c in cities:
 svg+=f'<circle cx="{c["x"]}" cy="{c["y"]}" r="4" fill="#0B2A4A"/>' if not c['warehouse'] else f'<rect x="{c["x"]-5}" y="{c["y"]-5}" width="10" height="10" fill="#F26B1D"/>'
(root/'public/images/russia-map.svg').write_text(svg+'</svg>');print('Map bytes:',len(svg))
