// Общие подписи интерфейса и примеры витрины компонентов.
export const labels = {
  razdelNeNayden: "Раздел не найден",
  hlebnyeKroshki: "Хлебные крошки",
  glavnaya: "Главная",
  razdelVRazrabotke: "Раздел в разработке",
  naGlavnuyu: "На главную",
  onegaLogistikGruzoperevozkiPoRossii:
    "Онега Логистик | Грузоперевозки по России",
  sOnegaLogistik: "%s | Онега Логистик",
  demonstratsionnyySaytTransportnoyKompaniiOnegaLogistik:
    "Демонстрационный сайт транспортной компании «Онега Логистик». Проект Shvetsov Studio.",
  pereytiKSoderzhimomu: "Перейти к содержимому",
  stranitsaNeNaydena: "Страница не найдена",
  proverteAdresIliPereyditeNaGlavnuyu:
    "Проверьте адрес или перейдите на главную страницу.",
  komponenty: "Компоненты",
  logotipIPalitra: "Логотип и палитра",
  tipografika: "Типографика",
  knopki: "Кнопки",
  polyaFormy: "Поля формы",
  kartochki: "Карточки",
  vkladki: "Вкладки",
  onegaGlavnaya: "Онега, главная",
  rasschitatDostavku: "Рассчитать доставку",
  kompaniya: "Компания",
  klientam: "Клиентам",
  myVSeti: "Мы в сети",
  otkrytPolnoeMenyu: "Открыть полное меню",
  osnovnayaNavigatsiya: "Основная навигация",
  uslugi: "Услуги",
  pochemuMy: "Почему мы",
  napravleniya: "Направления",
  tarify: "Тарифы",
  otsledit: "Отследить",
  kabinet: "Кабинет",
  vymyshlennyyTelefonDemoKompanii: "Вымышленный телефон демо-компании",
  rasschitat: "Рассчитать",
  polnoeMenyu: "Полное меню",
  vyberiteFormatPerevozki: "Выберите формат перевозки",
  zakrytMenyuUslug: "Закрыть меню услуг",
  podrobnee: "Подробнее",
  pomozhemVybratPodhodyaschiyFormatDostavki:
    "Поможем выбрать подходящий формат доставки.",
  voprosyIPomosch: "Вопросы и помощь",
  zakrytMenyu: "Закрыть меню",
  zakrytPolnoeMenyu: "Закрыть полное меню",
  vseRazdely: "Все разделы",
  oKompanii: "О компании",
  poznakomitsyaSNami: "Познакомиться с нами",
  moskva: "Москва",
  znakObedinyaetDvizhenieDorogiIPlavnye:
    "Знак объединяет движение дороги и плавные линии воды.",
  naSvetlomFone: "На светлом фоне",
  naTyomnomFone: "На тёмном фоне",
  tolkoZnak: "Только знак",
  interChetyreNachertaniyaTsifryIspolzuyutTablichnuyu:
    "Inter, четыре начертания. Цифры используют табличную ширину.",
  dvizhenieVashegoBiznesa: "Движение вашего бизнеса",
  kazhdayaPostavkaPodKontrolem: "Каждая поставка под контролем",
  podzagolovok2634600: "Подзаголовок · 26/34 · 600",
  dostavkaOtSkladaDoPoluchatelya: "Доставка от склада до получателя",
  sbornyeGruzy: "Сборные грузы",
  tekst1828400: "Текст · 18/28 · 400",
  myPodbiraemFormatPerevozkiPodObyom:
    "Мы подбираем формат перевозки под объём груза и маршрут. Согласуем детали до отправки и остаёмся на связи в пути.",
  tekst1624400: "Текст · 16/24 · 400",
  svedeniyaOPerevozkeSobranyVOdnom:
    "Сведения о перевозке собраны в одном месте.",
  podpis1420500: "Подпись · 14/20 · 500",
  demonstratsionnyeDannye: "Демонстрационные данные",
  knopkiISostoyaniya: "Кнопки и состояния",
  podrobneeObUsluge: "Подробнее об услуге",
  dokumenty: "Документы",
  sohranitIzmeneniya: "Сохранить изменения",
  netIzmeneniyDlyaSohraneniya: "Нет изменений для сохранения",
  demoProekt: "Демо-проект",
  stoimostSoglasovanaDoOtpravki: "Стоимость согласована до отправки",
  podpisiPoiskVDlinnyhSpiskahI:
    "Подписи, поиск в длинных списках и понятные сообщения об ошибках.",
  otkuda: "Откуда",
  formatGruza: "Формат груза",
  pallety: "Паллеты",
  korobki: "Коробки",
  negabaritnyyGruz: "Негабаритный груз",
  trebuetsyaSoglasovanieSMenedzherom: "Требуется согласование с менеджером",
  vesKg: "Вес, кг",
  naprimer250: "Например, 250",
  telefon: "Телефон",
  ukazhiteTelefonPolnostyu11Tsifr: "Укажите телефон полностью: 11 цифр.",
  kommentariyKPerevozke: "Комментарий к перевозке",
  razmeryUpakovkaIOsobennostiGruza: "Размеры, упаковка и особенности груза",
  kartochkiIPokazateli: "Карточки и показатели",
  primeryKomponentovChislaNizheVymyshleny:
    "Примеры компонентов. Числа ниже вымышлены.",
  gorodovVDemoSeti: "городов в демо-сети",
  skladovVDemoSeti: "складов в демо-сети",
  primerStoimosti: "пример стоимости",
  vkladkiIRaskrytie: "Вкладки и раскрытие",
  vyberiteVariant: "Выберите вариант",
  nichegoNeNaydeno: "Ничего не найдено",
  variantyPerevozki: "Варианты перевозки",
} as const;
